# Generated by Django 5.2.17 on 2026-09-02 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0004_store_vacation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Volume (ml)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='catalog.product', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='stores.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Produto da Loja',
                'verbose_name_plural': 'Produtos da Loja',
                'db_table': 'inventory_store_products',
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['store', 'product'], name='inventory_store_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product', 'volume_ml'), name='inventory_store_product_volume_uniq')],
            },
        ),
    ]
