# Generated by Django 5.2.17 on 2026-09-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_inpi_certificate_brand_social_contract'),
        ('stores', '0005_store_is_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='d2c_store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_brand', to='stores.store'),
        ),
    ]
