# Generated by Django 5.2.12 on 2026-08-31 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('legal_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio Olfativa')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='URL da Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Loja Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'stores',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['owner'], name='stores_owner_idx')],
            },
        ),
    ]
