# Generated by Django 5.2.12 on 2026-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover_url',
            field=models.URLField(blank=True, default='', verbose_name='URL da Capa'),
        ),
    ]
