# Generated by Django 5.2.12 on 2026-08-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cover_url',
            field=models.TextField(blank=True, default='', verbose_name='URL da Capa'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo_url',
            field=models.TextField(blank=True, default='', verbose_name='URL da Logo'),
        ),
    ]
