# Generated by Django 5.2.12 on 2026-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_cover_url_alter_store_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vacation_mode',
            field=models.BooleanField(default=False, verbose_name='Modo Férias'),
        ),
    ]
